# Generated by Django 6.0.4 on 2026-09-07 13:38

import django.db.models.deletion
import uuid
from django import VERSION as DJANGO_VERSION
from django.conf import settings
from django.db import migrations, models


def prepare_legacy_sessions(apps, schema_editor):
    Session = apps.get_model('hosting', 'HostingSession')
    for session in Session.objects.using(schema_editor.connection.alias).all().iterator():
        session.deployment_id = uuid.uuid4()
        # No host PID is trusted as a healthy container. Keep PID/path/command for
        # the worker's identity-checked cleanup, and preserve all saved projects.
        if session.status in ('starting', 'running'):
            session.status = 'failed'
            session.error_message = 'Legacy host deployment requires cleanup and a container restart.'
        session.save(update_fields=['deployment_id', 'status', 'error_message'])


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hostingsession_archive_document'),
        ('repository', '0013_archivedocument_system_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingsession',
            name='active_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='container_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='container_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='container_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='deployment_id',
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='health_status',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='internal_port',
            field=models.PositiveIntegerField(default=8080),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='restart_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='source_zip',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='hostingsession',
            name='stop_target',
            field=models.CharField(default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostingsession',
            name='archive_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_sessions', to='repository.archivedocument'),
        ),
        migrations.AlterField(
            model_name='hostingsession',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('extracting', 'Extracting'), ('building', 'Building'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('expired', 'Expired'), ('killed', 'Killed')], default='stopped', max_length=20),
        ),
        migrations.RunPython(prepare_legacy_sessions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hostingsession', name='deployment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='hostingsession',
            constraint=models.CheckConstraint(**{('condition' if DJANGO_VERSION >= (5, 1) else 'check'): models.Q(models.Q(('active_slot', 1), ('active_slot__isnull', False), ('status__in', ('uploaded', 'validating', 'extracting', 'building', 'starting', 'running', 'stopping'))), models.Q(models.Q(('status__in', ('uploaded', 'validating', 'extracting', 'building', 'starting', 'running', 'stopping')), _negated=True), ('active_slot__isnull', True)), _connector='OR')}, name='hosting_active_slot_matches_status'),
        ),
    ]
