# Generated by Django 6.0.4 on 2026-09-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_hostingsession_active_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingsession',
            name='health_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
