# Generated by Django 6.0.4 on 2026-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_hostingsession_health_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingsession',
            name='project_type',
            field=models.CharField(choices=[('static', 'HTML / CSS / JavaScript'), ('php', 'PHP'), ('python', 'Python'), ('node', 'Node / JavaScript'), ('ruby', 'Ruby'), ('cpp', 'C++')], max_length=20),
        ),
    ]
