# Generated by Django 6.0.4 on 2026-09-13 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_add_fullstack_runtime'),
        ('repository', '0014_researchsubmissionrequest_research_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingsession',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='hostingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('archive_document',), name='hosting_one_default_per_archive'),
        ),
    ]
