# Generated by Django 6.0.4 on 2026-09-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_hostingsession_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingsession',
            name='tunnel_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
