# Generated by Django 6.0.2 on 2026-04-10 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_collabprojectfile'),
        ('repository', '0004_backfill_legacy_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabproject',
            name='linked_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_projects', to='repository.repository'),
        ),
    ]
