from django.urls import path
from .views import (
    ResearchOutputListCreateView,
    ResearchOutputDetailView,
    ApproveOutputView,
    DownloadFileView,
    PreviewFileView,
    ReviseOutputView,
    VersionHistoryView,
    RollbackVersionView,
    BackupView,
    RestoreView,
    StatsView,
    ExportCSVView,
    RepositoryListCreateView,
    RepositoryDetailView,
    RepositoryVersionHistoryView,
    RepositoryReviseView,
    RepositoryRelatedDocumentsView,
    RepositoryDownloadView,
    RepositoryPreviewView,
    RepositoryBrowseFileView,
    RepositoryFileContentView,
    RunRepositoryCodeView,
    RepositoryRunnableFilesView,
    ArchiveDocumentListCreateView,
    ArchiveDocumentDetailView,
    ArchiveDocumentDownloadView,
    ArchiveDocumentPreviewView,
    ArchiveDocumentVersionHistoryView,
    ArchiveDocumentReviseView,
    ArchiveDocumentReviewView,
    DepartmentListCreateView,
    DepartmentDetailView,
    CourseListCreateView,
    CourseDetailView,
)

urlpatterns = [
    path('departments/', DepartmentListCreateView.as_view(), name='department-list-create'),
    path('departments/<int:pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    path('courses/', CourseListCreateView.as_view(), name='course-list-create'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('repositories/', RepositoryListCreateView.as_view(), name='repository-list-create'),
    path('repositories/<int:pk>/', RepositoryDetailView.as_view(), name='repository-detail'),
    path('repositories/<int:pk>/versions/', RepositoryVersionHistoryView.as_view(), name='repository-versions'),
    path('repositories/<int:pk>/revise/', RepositoryReviseView.as_view(), name='repository-revise'),
    path('repositories/<int:pk>/documents/', RepositoryRelatedDocumentsView.as_view(), name='repository-documents'),
    path('repositories/<int:pk>/download/', RepositoryDownloadView.as_view(), name='repository-download'),
    path('repositories/<int:pk>/download/<int:file_id>/', RepositoryDownloadView.as_view(), name='repository-file-download'),
    path('repositories/<int:pk>/preview/', RepositoryPreviewView.as_view(), name='repository-preview'),
    path('repositories/<int:pk>/preview/<int:file_id>/', RepositoryPreviewView.as_view(), name='repository-file-preview'),
    path('repositories/<int:pk>/browse/', RepositoryBrowseFileView.as_view(), name='repository-browse'),
    path('repositories/<int:pk>/browse/<int:file_id>/', RepositoryBrowseFileView.as_view(), name='repository-file-browse'),
    path('repositories/<int:pk>/content/', RepositoryFileContentView.as_view(), name='repository-content'),
    path('repositories/<int:pk>/content/<int:file_id>/', RepositoryFileContentView.as_view(), name='repository-file-content'),
    path('repositories/<int:pk>/run/', RunRepositoryCodeView.as_view(), name='repository-run'),
    path('repositories/<int:pk>/run/<int:file_id>/', RunRepositoryCodeView.as_view(), name='repository-file-run'),
    path('repositories/<int:pk>/runnable-files/', RepositoryRunnableFilesView.as_view(), name='repository-runnable-files'),
    path('repositories/<int:pk>/runnable-files/<int:file_id>/', RepositoryRunnableFilesView.as_view(), name='repository-file-runnable-files'),
    path('archives/', ArchiveDocumentListCreateView.as_view(), name='archive-list-create'),
    path('archives/<int:pk>/', ArchiveDocumentDetailView.as_view(), name='archive-detail'),
    path('archives/<int:pk>/versions/', ArchiveDocumentVersionHistoryView.as_view(), name='archive-versions'),
    path('archives/<int:pk>/revise/', ArchiveDocumentReviseView.as_view(), name='archive-revise'),
    path('archives/<int:pk>/review/', ArchiveDocumentReviewView.as_view(), name='archive-review'),
    path('archives/<int:pk>/download/', ArchiveDocumentDownloadView.as_view(), name='archive-download'),
    path('archives/<int:pk>/download/<int:version_id>/', ArchiveDocumentDownloadView.as_view(), name='archive-version-download'),
    path('archives/<int:pk>/preview/', ArchiveDocumentPreviewView.as_view(), name='archive-preview'),
    path('archives/<int:pk>/preview/<int:version_id>/', ArchiveDocumentPreviewView.as_view(), name='archive-version-preview'),
    path('', ResearchOutputListCreateView.as_view(), name='output-list-create'),
    path('stats/', StatsView.as_view(), name='output-stats'),
    path('export/csv/', ExportCSVView.as_view(), name='output-export-csv'),
    path('backup/', BackupView.as_view(), name='backup'),
    path('restore/', RestoreView.as_view(), name='restore'),
    path('<int:pk>/', ResearchOutputDetailView.as_view(), name='output-detail'),
    path('<int:pk>/approve/', ApproveOutputView.as_view(), name='output-approve'),
    path('<int:pk>/download/', DownloadFileView.as_view(), name='output-download'),
    path('<int:pk>/download/<int:file_id>/', DownloadFileView.as_view(), name='file-download'),
    path('<int:pk>/preview/', PreviewFileView.as_view(), name='output-preview'),
    path('<int:pk>/preview/<int:file_id>/', PreviewFileView.as_view(), name='file-preview'),
    path('<int:pk>/revise/', ReviseOutputView.as_view(), name='output-revise'),
    path('<int:pk>/versions/', VersionHistoryView.as_view(), name='output-versions'),
    path('<int:pk>/rollback/', RollbackVersionView.as_view(), name='output-rollback'),
]
