from django.urls import path
from .views import (
    ResearchOutputListCreateView,
    ResearchOutputDetailView,
    ApproveOutputView,
    DownloadFileView,
    PreviewFileView,
    ReviseOutputView,
    VersionHistoryView,
    RollbackVersionView,
    BackupView,
    StatsView,
    ExportCSVView,
    BrowseFileView,
    FileContentView,
    RunRepositoryFileView,
    ListRunnableFilesView,
    RepositoryListCreateView,
    RepositoryDetailView,
    RepositoryVersionHistoryView,
    RepositoryReviseView,
    RepositoryRelatedDocumentsView,
    RepositoryDownloadView,
    RepositoryPreviewView,
    RepositoryBrowseFileView,
    RepositoryFileContentView,
    RunRepositoryCodeView,
    RepositoryRunnableFilesView,
    ArchiveDocumentListCreateView,
    ArchiveDocumentDetailView,
    ArchiveDocumentDownloadView,
    ArchiveDocumentPreviewView,
)

urlpatterns = [
    path('repos/', RepositoryListCreateView.as_view(), name='repository-list-create'),
    path('repos/<int:pk>/', RepositoryDetailView.as_view(), name='repository-detail'),
    path('repos/<int:pk>/versions/', RepositoryVersionHistoryView.as_view(), name='repository-versions'),
    path('repos/<int:pk>/revise/', RepositoryReviseView.as_view(), name='repository-revise'),
    path('repos/<int:pk>/documents/', RepositoryRelatedDocumentsView.as_view(), name='repository-documents'),
    path('repos/<int:pk>/download/', RepositoryDownloadView.as_view(), name='repository-download'),
    path('repos/<int:pk>/download/<int:file_id>/', RepositoryDownloadView.as_view(), name='repository-file-download'),
    path('repos/<int:pk>/preview/', RepositoryPreviewView.as_view(), name='repository-preview'),
    path('repos/<int:pk>/preview/<int:file_id>/', RepositoryPreviewView.as_view(), name='repository-file-preview'),
    path('repos/<int:pk>/browse/', RepositoryBrowseFileView.as_view(), name='repository-browse'),
    path('repos/<int:pk>/browse/<int:file_id>/', RepositoryBrowseFileView.as_view(), name='repository-file-browse'),
    path('repos/<int:pk>/file-content/', RepositoryFileContentView.as_view(), name='repository-file-content'),
    path('repos/<int:pk>/file-content/<int:file_id>/', RepositoryFileContentView.as_view(), name='repository-file-content-by-id'),
    path('repos/<int:pk>/run/', RunRepositoryCodeView.as_view(), name='repository-run'),
    path('repos/<int:pk>/run/<int:file_id>/', RunRepositoryCodeView.as_view(), name='repository-file-run'),
    path('repos/<int:pk>/runnable/', RepositoryRunnableFilesView.as_view(), name='repository-runnable'),
    path('repos/<int:pk>/runnable/<int:file_id>/', RepositoryRunnableFilesView.as_view(), name='repository-file-runnable'),
    path('archives/', ArchiveDocumentListCreateView.as_view(), name='archive-list-create'),
    path('archives/<int:pk>/', ArchiveDocumentDetailView.as_view(), name='archive-detail'),
    path('archives/<int:pk>/download/', ArchiveDocumentDownloadView.as_view(), name='archive-download'),
    path('archives/<int:pk>/preview/', ArchiveDocumentPreviewView.as_view(), name='archive-preview'),
    path('', ResearchOutputListCreateView.as_view(), name='output-list-create'),
    path('stats/', StatsView.as_view(), name='output-stats'),
    path('export/csv/', ExportCSVView.as_view(), name='output-export-csv'),
    path('backup/', BackupView.as_view(), name='backup'),
    path('<int:pk>/', ResearchOutputDetailView.as_view(), name='output-detail'),
    path('<int:pk>/approve/', ApproveOutputView.as_view(), name='output-approve'),
    path('<int:pk>/download/', DownloadFileView.as_view(), name='output-download'),
    path('<int:pk>/download/<int:file_id>/', DownloadFileView.as_view(), name='file-download'),
    path('<int:pk>/preview/', PreviewFileView.as_view(), name='output-preview'),
    path('<int:pk>/preview/<int:file_id>/', PreviewFileView.as_view(), name='file-preview'),
    path('<int:pk>/revise/', ReviseOutputView.as_view(), name='output-revise'),
    path('<int:pk>/versions/', VersionHistoryView.as_view(), name='output-versions'),
    path('<int:pk>/rollback/', RollbackVersionView.as_view(), name='output-rollback'),
    path('<int:pk>/browse/', BrowseFileView.as_view(), name='output-browse'),
    path('<int:pk>/browse/<int:file_id>/', BrowseFileView.as_view(), name='file-browse'),
    path('<int:pk>/file-content/', FileContentView.as_view(), name='output-file-content'),
    path('<int:pk>/file-content/<int:file_id>/', FileContentView.as_view(), name='file-content'),
    # Repository code runner
    path('<int:pk>/run/', RunRepositoryFileView.as_view(), name='output-run'),
    path('<int:pk>/run/<int:file_id>/', RunRepositoryFileView.as_view(), name='file-run'),
    path('<int:pk>/runnable/', ListRunnableFilesView.as_view(), name='output-runnable'),
    path('<int:pk>/runnable/<int:file_id>/', ListRunnableFilesView.as_view(), name='file-runnable'),
]
