# Generated by Django 6.0.2 on 2026-02-23 01:18

import django.db.models.deletion
import repository.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('output_type', models.CharField(choices=[('thesis', 'Thesis Manuscript'), ('software', 'Software Project'), ('sourcecode', 'Source Code'), ('documentation', 'Documentation'), ('other', 'Other')], default='thesis', max_length=30)),
                ('department', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(max_length=300)),
                ('adviser', models.CharField(blank=True, max_length=300)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=repository.models.upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('change_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('research_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repository.researchoutput')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
