# Generated by Django 6.0.2 on 2026-09-06 15:50

import django.db.models.deletion
import repository.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_remove_archivedocument_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='system_file',
            field=models.FileField(blank=True, upload_to=repository.models.archive_system_upload_to),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='system_file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='system_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='file',
            field=models.FileField(blank=True, upload_to=repository.models.archive_upload_to),
        ),
        migrations.CreateModel(
            name='ResearchSubmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('submission_type', models.CharField(choices=[('research_paper', 'Research paper'), ('executable_system', 'Executable system'), ('paper_and_system', 'Research paper and executable system')], default='research_paper', max_length=30)),
                ('author', models.CharField(max_length=300)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('system_details', models.TextField(blank=True)),
                ('proposed_system_link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Returned for revision')], default='pending', max_length=30)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_archive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission_request', to='repository.archivedocument')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_submission_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_research_submission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queued_at', 'id'],
                'indexes': [models.Index(fields=['status', 'queued_at', 'id'], name='repository__status_0ad6ec_idx'), models.Index(fields=['requested_by', 'created_at'], name='repository__request_ad1625_idx')],
            },
        ),
    ]
