# Generated by Django 6.0.4 on 2026-09-13 05:50

import repository.models
import repository.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_archivedocument_system_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='research_file',
            field=models.FileField(blank=True, storage=repository.storage.SubmissionStorage, upload_to=repository.models.submission_upload_to),
        ),
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='research_file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='research_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='system_file',
            field=models.FileField(blank=True, storage=repository.storage.SubmissionStorage, upload_to=repository.models.submission_upload_to),
        ),
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='system_file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsubmissionrequest',
            name='system_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
